dist: trusty
language: ruby
email: false
cache:
  directories:
    - ../bundle

bundler_args: "--binstubs --standalone --without documentation --jobs 3 --retry 3 --path ../bundle"

#before_install:
#  - echo "Warning installing older versions of Rubygems / Bundler"
#  - yes | gem update --system '2.7.8' --force
#  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
#  - gem install bundler -v '< 2'

script:
  - bundle exec rspec

rvm:
  - 1.9.3
  - 2.0.0
