dist: trusty
language: ruby
email: false
cache:
  directories:
    - ../bundle
apt:
  packages:
    - libssl1.0-dev
    - openssl1.0

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug --dev"
    - CC_TEST_REPORTER_ID=b371af9d80b8b1f593e87d11c20137cf7573149a6296278715acd3fa48ddc280
bundler_args: "--binstubs --standalone --without documentation --jobs 3 --retry 3 --path ../bundle"

before_install:
  - echo "Warning installing older versions of Rubygems / Bundler"
  - yes | gem update --system '2.7.8' --force
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-1.7

matrix:
  include:
    - rvm: jruby-1.7
      env: JRUBY_OPTS='--dev --1.8'
  fast_finish: true