dist: trusty
language: ruby
email: false
cache:
  directories:
    - ../bundle

bundler_args: "--binstubs --standalone --without documentation --jobs 3 --retry 3 --path ../bundle"

script:
  - bundle exec rspec

rvm:
  - 1.9.3
  - 2.0.0
