name: Code Style Checks

on:
  push:
    branches:
      - 'main'
      - 'master'
      - '*-maintenance'
      - '*-dev'
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    name: Rubocop
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - 2.7
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: Run Rubocop
        run: bundle exec rubocop -DESP