name: Unit Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
      - '*-maintenance'
      - '*-dev'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        ruby:
          - 3.0.0-rc1
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3
          - 2.2
          - 2.1
          - ruby-head
        include:
          - ruby: jruby-9.2.13.0
            env:
              JRUBY_OPTS: "-Xcli.debug=true --debug --dev"
          - ruby: jruby-9.1.17.0
            bundler: 1
            os: ubuntu-18.04
            env:
              JRUBY_OPTS: "-Xcli.debug=true --debug --dev"
    continue-on-error: ${{ matrix.allow_failure || endsWith(matrix.ruby, 'head') }}
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler || 2 }}
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --jobs 3 --retry 3 --binstubs --standalone
      - name: Run tests
        run: bundle exec rake test
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
        if: "startsWith(matrix.ruby, '2.7')"
        env:
          CC_TEST_REPORTER_ID: b371af9d80b8b1f593e87d11c20137cf7573149a6296278715acd3fa48ddc280
